[2023-02-20 21:53:50,792] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:53:48.811666+00:00 [queued]>
[2023-02-20 21:53:50,813] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:53:48.811666+00:00 [queued]>
[2023-02-20 21:53:50,814] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 21:53:50,816] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-02-20 21:53:50,817] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 21:53:50,844] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-20 21:53:48.811666+00:00
[2023-02-20 21:53:50,853] {standard_task_runner.py:52} INFO - Started process 1034 to run task
[2023-02-20 21:53:50,861] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-20T21:53:48.811666+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmpl4n2oq6_', '--error-file', '/tmp/tmpirnyuw4a']
[2023-02-20 21:53:50,863] {standard_task_runner.py:77} INFO - Job 141: Subtask launching_chrome
[2023-02-20 21:53:50,964] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:53:48.811666+00:00 [running]> on host 1b319cb4c67b
[2023-02-20 21:53:51,071] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T21:53:48.811666+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T21:53:48.811666+00:00
[2023-02-20 21:53:51,076] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-20 21:53:51,262] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 110.0.5481
[2023-02-20 21:53:51,535] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
[2023-02-20 21:54:11,295] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 141, in launch_chrome
    h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
#0 0x55709a257d93 <unknown>
#1 0x55709a0262d7 <unknown>
#2 0x55709a062caa <unknown>
#3 0x55709a062db1 <unknown>
#4 0x55709a0a08f4 <unknown>
#5 0x55709a08661d <unknown>
#6 0x55709a09e619 <unknown>
#7 0x55709a086353 <unknown>
#8 0x55709a055e40 <unknown>
#9 0x55709a057038 <unknown>
#10 0x55709a2ab8be <unknown>
#11 0x55709a2af8f0 <unknown>
#12 0x55709a28ff90 <unknown>
#13 0x55709a2b0b7d <unknown>
#14 0x55709a281578 <unknown>
#15 0x55709a2d5348 <unknown>
#16 0x55709a2d54d6 <unknown>
#17 0x55709a2ef341 <unknown>
#18 0x7f4682dc1fa3 start_thread

[2023-02-20 21:54:11,331] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=launching_chrome, execution_date=20230220T215348, start_date=20230220T215350, end_date=20230220T215411
[2023-02-20 21:54:11,379] {standard_task_runner.py:92} ERROR - Failed to execute job 141 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 141, in launch_chrome
    h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
#0 0x55709a257d93 <unknown>
#1 0x55709a0262d7 <unknown>
#2 0x55709a062caa <unknown>
#3 0x55709a062db1 <unknown>
#4 0x55709a0a08f4 <unknown>
#5 0x55709a08661d <unknown>
#6 0x55709a09e619 <unknown>
#7 0x55709a086353 <unknown>
#8 0x55709a055e40 <unknown>
#9 0x55709a057038 <unknown>
#10 0x55709a2ab8be <unknown>
#11 0x55709a2af8f0 <unknown>
#12 0x55709a28ff90 <unknown>
#13 0x55709a2b0b7d <unknown>
#14 0x55709a281578 <unknown>
#15 0x55709a2d5348 <unknown>
#16 0x55709a2d54d6 <unknown>
#17 0x55709a2ef341 <unknown>
#18 0x7f4682dc1fa3 start_thread

[2023-02-20 21:54:11,425] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-20 21:54:11,483] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
