[2023-02-20 21:59:12,575] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:53:48.811666+00:00 [queued]>
[2023-02-20 21:59:12,631] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:53:48.811666+00:00 [queued]>
[2023-02-20 21:59:12,632] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 21:59:12,633] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-02-20 21:59:12,634] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 21:59:12,662] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-20 21:53:48.811666+00:00
[2023-02-20 21:59:12,669] {standard_task_runner.py:52} INFO - Started process 1358 to run task
[2023-02-20 21:59:12,682] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-20T21:53:48.811666+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmp0pus1kgb', '--error-file', '/tmp/tmp4w5e0ykt']
[2023-02-20 21:59:12,684] {standard_task_runner.py:77} INFO - Job 142: Subtask launching_chrome
[2023-02-20 21:59:12,788] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:53:48.811666+00:00 [running]> on host 1b319cb4c67b
[2023-02-20 21:59:12,888] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T21:53:48.811666+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T21:53:48.811666+00:00
[2023-02-20 21:59:12,891] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-20 21:59:13,399] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 110.0.5481
[2023-02-20 21:59:13,836] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
[2023-02-20 21:59:42,866] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 141, in launch_chrome
    h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
#0 0x55e8fa1dfd93 <unknown>
#1 0x55e8f9fae2d7 <unknown>
#2 0x55e8f9feacaa <unknown>
#3 0x55e8f9feadb1 <unknown>
#4 0x55e8fa0288f4 <unknown>
#5 0x55e8fa00e61d <unknown>
#6 0x55e8fa026619 <unknown>
#7 0x55e8fa00e353 <unknown>
#8 0x55e8f9fdde40 <unknown>
#9 0x55e8f9fdf038 <unknown>
#10 0x55e8fa2338be <unknown>
#11 0x55e8fa2378f0 <unknown>
#12 0x55e8fa217f90 <unknown>
#13 0x55e8fa238b7d <unknown>
#14 0x55e8fa209578 <unknown>
#15 0x55e8fa25d348 <unknown>
#16 0x55e8fa25d4d6 <unknown>
#17 0x55e8fa277341 <unknown>
#18 0x7f3e468fcfa3 start_thread

[2023-02-20 21:59:42,999] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=tutorial, task_id=launching_chrome, execution_date=20230220T215348, start_date=20230220T215912, end_date=20230220T215942
[2023-02-20 21:59:43,064] {standard_task_runner.py:92} ERROR - Failed to execute job 142 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 141, in launch_chrome
    h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
#0 0x55e8fa1dfd93 <unknown>
#1 0x55e8f9fae2d7 <unknown>
#2 0x55e8f9feacaa <unknown>
#3 0x55e8f9feadb1 <unknown>
#4 0x55e8fa0288f4 <unknown>
#5 0x55e8fa00e61d <unknown>
#6 0x55e8fa026619 <unknown>
#7 0x55e8fa00e353 <unknown>
#8 0x55e8f9fdde40 <unknown>
#9 0x55e8f9fdf038 <unknown>
#10 0x55e8fa2338be <unknown>
#11 0x55e8fa2378f0 <unknown>
#12 0x55e8fa217f90 <unknown>
#13 0x55e8fa238b7d <unknown>
#14 0x55e8fa209578 <unknown>
#15 0x55e8fa25d348 <unknown>
#16 0x55e8fa25d4d6 <unknown>
#17 0x55e8fa277341 <unknown>
#18 0x7f3e468fcfa3 start_thread

[2023-02-20 21:59:43,283] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-20 21:59:43,480] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
